version: '3.8'
services:
  redis-master:
    image: redis
    ports:
    - 6379:6379
  redis-slave:
    image: gcr.io/google_samples/gb-redisslave:v3
    ports:
    - 6380:6380
    environment:
      GET_HOSTS_FROM: dns
  front-end:
    image: gcr.io/google-samples/gb-frontend:v4
    ports:
    - 80:80
    environment:
      GET_HOSTS_FROM: dns
