version: '3.8'
services:
  db:
    image: postgres
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db

  redis:
    image: redis
    ports:
    - 6379:6379
    

  votes:
    image: kodekloud/examplevotingapp_vote:v1
    ports:
    - 80:80

  results:
    image: kodekloud/examplevotingapp_result:v1
    ports:
    - 8080:80

  worker:
    image: kodekloud/examplevotingapp_worker:v1
